version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: abronan/rust-circleci:latest

    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
        name: install cargo-make
        command: which cargo-make || cargo install cargo-make
      - run:
        name: ci flow
        command: cargo make ci-flow
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"